#!/usr/bin/env bash
# Run a password-protected Redis per environment. Prod and staging each get
# their OWN container, host port, data volume and config, so they never share
# keys or BullMQ queues on the same server.
#
#   env      container          host port   volume
#   prod     ws-redis-prod      6380        ws-redis-prod-data
#   staging  ws-redis-staging   6381        ws-redis-staging-data
#
# Run from the repo root of that environment's checkout:
#   ./scripts/redis.sh prod              # start (or re-create) + verify AUTH
#   ./scripts/redis.sh staging           # same for staging
#   ./scripts/redis.sh prod status       # container + ping with/without password
#   ./scripts/redis.sh prod logs         # tail logs
#   ./scripts/redis.sh prod stop         # remove container (data volume kept)
#
# Reads REDIS_PASSWORD / REDIS_PORT from the environment, falling back to .env
# (override the file with ENV_FILE=...). Each env's app .env must match:
#   REDIS_HOST=localhost  REDIS_PORT=<port above>  REDIS_PASSWORD=<its own password>
# Then restart the app so it reconnects:
#   pm2 reload ecosystem.config.cjs --env <production|staging> --update-env

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

TARGET="${1:-}"
ACTION="${2:-start}"

case "$TARGET" in
  prod|production) TARGET=prod; DEFAULT_PORT=6380; PM2_ENV=production ;;
  staging) DEFAULT_PORT=6381; PM2_ENV=staging ;;
  *) echo "Usage: $0 <prod|staging> [start|status|logs|stop]" >&2; exit 1 ;;
esac

ENV_FILE="${ENV_FILE:-${ROOT}/.env}"

# Read KEY from .env without sourcing it (values may contain $, @, spaces...).
read_env() {
  [[ -f "$ENV_FILE" ]] || return 0
  grep -E "^[[:space:]]*$1[[:space:]]*=" "$ENV_FILE" | tail -n 1 \
    | sed -E "s/^[^=]*=[[:space:]]*//; s/[[:space:]]+$//; s/^\"(.*)\"$/\1/; s/^'(.*)'$/\1/"
}

REDIS_PASSWORD="${REDIS_PASSWORD:-$(read_env REDIS_PASSWORD)}"
REDIS_PORT="${REDIS_PORT:-$(read_env REDIS_PORT)}"
REDIS_PORT="${REDIS_PORT:-$DEFAULT_PORT}"

CONTAINER="ws-redis-${TARGET}"
VOLUME="ws-redis-${TARGET}-data"
IMAGE="${REDIS_IMAGE:-redis:7-alpine}"
MAXMEMORY="${REDIS_MAXMEMORY:-512mb}"
# BullMQ requires `noeviction` — an LRU policy can silently evict queued jobs.
EVICTION="${REDIS_EVICTION:-noeviction}"
CONF_DIR="${ROOT}/.redis-${TARGET}"
CONF_FILE="${CONF_DIR}/redis.conf"

cli() {
  # REDISCLI_AUTH keeps the password out of `ps` / shell history.
  docker exec -e REDISCLI_AUTH="$REDIS_PASSWORD" "$CONTAINER" redis-cli "$@"
}

require_password() {
  if [[ -z "$REDIS_PASSWORD" ]]; then
    echo "REDIS_PASSWORD is not set (env or ${ENV_FILE})." >&2
    echo "Generate one:  openssl rand -base64 36 | tr -d '/+='" >&2
    exit 1
  fi
  if [[ "${#REDIS_PASSWORD}" -lt 16 ]]; then
    echo "REDIS_PASSWORD is shorter than 16 chars — use a strong random password." >&2
    exit 1
  fi
}

write_conf() {
  mkdir -p "$CONF_DIR"
  chmod 700 "$CONF_DIR"
  # Password lives in this file, not in `docker inspect` args.
  cat > "$CONF_FILE" <<EOF
# Generated by scripts/redis.sh (${TARGET}) — do not commit.
bind 0.0.0.0
protected-mode yes
port 6379
requirepass ${REDIS_PASSWORD}

maxmemory ${MAXMEMORY}
maxmemory-policy ${EVICTION}

appendonly yes
appendfsync everysec

# Block dangerous commands for anyone who gets hold of the password.
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command DEBUG ""
EOF
  # redis in the container runs as a non-root uid and must be able to read it;
  # the 700 parent dir keeps other host users out.
  chmod 644 "$CONF_FILE"
}

port_owner() {
  docker ps --format '{{.Names}} {{.Ports}}' | grep -E "[:.]${REDIS_PORT}->" | awk '{print $1}' || true
}

start() {
  require_password

  local owner
  owner="$(port_owner)"
  if [[ -n "$owner" && "$owner" != "$CONTAINER" ]]; then
    echo "Port ${REDIS_PORT} is already used by container '${owner}'." >&2
    echo "Stop it, or use another port: set REDIS_PORT in ${ENV_FILE} and re-run." >&2
    exit 1
  fi

  write_conf
  docker volume create "$VOLUME" >/dev/null

  if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    echo "Re-creating ${CONTAINER} (data in volume ${VOLUME} is kept)..."
    docker rm -f "$CONTAINER" >/dev/null
  else
    echo "Creating ${CONTAINER}..."
  fi

  docker run -d \
    --name "$CONTAINER" \
    --restart always \
    -p "127.0.0.1:${REDIS_PORT}:6379" \
    -v "${VOLUME}:/data" \
    -v "${CONF_FILE}:/usr/local/etc/redis/redis.conf:ro" \
    "$IMAGE" redis-server /usr/local/etc/redis/redis.conf >/dev/null

  echo "Waiting for Redis..."
  for i in $(seq 1 30); do
    if [[ "$(cli ping 2>/dev/null)" == "PONG" ]]; then
      break
    fi
    if [[ "$i" -eq 30 ]]; then
      echo "Redis did not become ready. Check: docker logs ${CONTAINER}" >&2
      exit 1
    fi
    sleep 1
  done

  # Prove AUTH is actually enforced: an unauthenticated ping must be rejected.
  if docker exec "$CONTAINER" redis-cli ping 2>&1 | grep -q PONG; then
    echo "WARNING: Redis answered WITHOUT a password — requirepass is not active!" >&2
    exit 1
  fi

  echo "OK: ${CONTAINER} on 127.0.0.1:${REDIS_PORT}, password required, policy ${EVICTION}."
  echo "App .env must have: REDIS_HOST=localhost REDIS_PORT=${REDIS_PORT} REDIS_PASSWORD=<same>"
  echo "Then:  pm2 reload ecosystem.config.cjs --env ${PM2_ENV} --update-env"
}

status() {
  docker ps -a --filter "name=^${CONTAINER}$" --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
  require_password
  echo -n "AUTH ping: "; cli ping || true
  echo -n "No-auth ping (should be NOAUTH): "; docker exec "$CONTAINER" redis-cli ping 2>&1 || true
  cli info keyspace | tail -n +2 || true
}

case "$ACTION" in
  start) start ;;
  status) status ;;
  logs) docker logs -f --tail 100 "$CONTAINER" ;;
  stop) docker rm -f "$CONTAINER" && echo "Stopped ${CONTAINER} (volume ${VOLUME} kept)." ;;
  *) echo "Usage: $0 <prod|staging> [start|status|logs|stop]" >&2; exit 1 ;;
esac
