-- Course-plan leak fix. ws_package_course_ebook_price (shared package/course/ebook
-- pricing) holds legacy course-plan rows referencing course ids up to 113, but
-- ws_course only has courses up to id 83 — so newly created courses were getting
-- ids in the 84..113 range and "inheriting" 120 orphaned plan rows from
-- long-deleted courses (GET /admin/courses/:id/plans returned them).
--
-- Push the auto-increment past the highest course_id referenced anywhere so new
-- courses never collide with orphaned pricing. Non-destructive (only affects
-- future ids). On production, recompute the value as:
--   GREATEST( (SELECT MAX(id) FROM ws_course),
--             (SELECT MAX(course_id) FROM ws_package_course_ebook_price) ) + 1
ALTER TABLE ws_course AUTO_INCREMENT = 114;
